### ISSUE TITLE
root privileges?

### ISSUE THREAD

**Issue by greyltc** [icshwi/e3#20]
Why do `./e3.bash base` and `./e3.bash req` ask for my sudo password?

**Comment by jeonghanlee** [comment]
@greyltc , please try it with the following commands, and let me know
```
bash e3_building_config.bash -t ${HOME}/epics setup
bash e3.bash base
bash e3.bash req
```
It was due to old READM.md in this repository.

**Comment by jeonghanlee** [comment]
Ah! I also find one strange option in e3.bash, which I made a long ago, that may ask you sudo password whether one has the right permission or not.  I will come back soon.

**Comment by jeonghanlee** [comment]
Please try it with the above commands. With efc0912 , I removed the hidden SUDO option in case the cloned directories exist.  It is more reasonable to remove it, because of the privileges consistency. I will think a better logic to handle "clone" repository directories when one would like to switch between normal user and root privileges.

**Comment by greyltc** [comment]
fixed! perfect! thanks!
