### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by greyltc** [icshwi/e3#21]
```
pi@raspberrypi:~/git/e3 $ bash e3.bash base
[sudo] password for pi: 
Cleaning .... e3-base
>> e3-base
>> No target directroy is found, Cloning...

Cloning into 'e3-base'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 547 (delta 10), reused 12 (delta 5), pack-reused 526
Receiving objects: 100% (547/547), 100.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (309/309), done.

mkdir: cannot create directory ‘/home/grey’: Permission denied
make: /home/pi/git/e3/e3-base/epics-base/startup/EpicsHostArch.pl: Command not found
Can't open perl script "/home/pi/git/e3/e3-base/epics-base/src/tools/EpicsHostArch.pl": No such file or directory
```
Two issues here:
`mkdir: cannot create directory ‘/home/grey’: Permission denied` why is this directory trying to be created!?
and
`Can't open perl script "/home/pi/git/e3/e3-base/epics-base/src/tools/EpicsHostArch.pl": No such file or directory`

**Comment by jeonghanlee** [comment]
@greyltc , the second issue I've explained to you is related with the latest epics base change. 
When I look at your messges in the first issue, I have the following question:
* you are in pi user, in order to create /home/grey directory. Does your pi has the right permission to access /home/grey path? 

I would like to suggest to run this `e3.bash base` after the following command
```
bash e3_building_config.bash -t ${HOME}/epics setup
bash e3.bash base
```

Please let me know what you get.  I've found the README was old, and also updated with that command.

**Comment by greyltc** [comment]
the updated readme solves this. thanks!
